---
- name: Install
  hosts: all
  become: true
  become_method: ansible.builtin.sudo

  vars:
    virtualbox_version: 7.1
    virtualbox_users:
    - ubuntu
    - vagrant

  roles:
  - name: andrelohmann.root_colored_prompt
  - name: ansible-role-virtualbox

...
