---
- name: Converge
  hosts: all
  become: true
  become_method: sudo
  vars:
    virtualbox_version: 7.1
  tasks:
  - name: "Include andrelohmann.virtualbox"
    include_role:
      name: "andrelohmann.virtualbox"
...
