---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:

  - name: Get virtualbox version
    ansible.builtin.command: vboxmanage -v
    register: virtualbox_status
    changed_when: false

  - name: Dump virtualbox status
    ansible.builtin.debug:
      var: virtualbox_status

  - name: Assert virtualbox has version 7.1
    ansible.builtin.assert:
      that: virtualbox_status.stdout is search('7.1')

...
